name: Build and Publish
on:
  workflow_dispatch:
    inputs:
      version:
        description: Version
        required: true
        type: string

env:
  VERSION: ${{ inputs.version }}
jobs:
  container_publish:
    runs-on: ubuntu-latest
    permisions:
      packages: write
    steps:
      - uses: actions/checkout@v2
      
      - name: Retrieve version
        run: sh ./build-container.sh
        id: release-file

      # https://github.com/marketplace/actions/push-to-ghcr
      - name: Build and publish a Docker image for ${{ github.repository }}
        uses: macbre/push-to-ghcr@master
        env:
          FILE_NAME: ${{ steps.release-file.outputs.filename }}
        with:
          image_name: ${{ github.repository }}  # it will be lowercased internally
          github_token: ${{ secrets.GITHUB_TOKEN }}
          dockerfile: ./ContainerFile
          extra_args: "--build-arg VERSION=${{ env.VERSION }} --build-arg FILE_NAME=${{ steps.release-file.outputs.filename }}"
